import { contact } from "../data/contact";
import { prices } from "../data/prices";
import { JsonLd, buildBreadcrumbSchema, buildGraphSchema, buildLocalBusinessSchema } from "../components/seo/JsonLd";
import { SEO_LANDING_SLUGS, type SeoLandingSlug } from "../data/seoLandingSlugs";
export { SEO_LANDING_SLUGS } from "../data/seoLandingSlugs";

const seaterBestFor: Record<string, string> = { "12": "Small families and airport transfers", "16": "Wedding guest shuttles and day trips", "18": "Wedding parties and group tours", "20": "Corporate offsites", "24": "Baraat and large groups" };
const money = (value: number) => `₹${value.toLocaleString("en-IN")}`;
const cityTitle = (slug: string) => slug.split("-").map((word) => word[0]?.toUpperCase() + word.slice(1)).join(" ");

function pageModel(slug: SeoLandingSlug) {
  const seater = slug.match(/^(12|16|18|20|24)-seater/)?.[1];
  if (slug === "tempo-traveller-on-rent-agra" || seater) {
    const label = seater ? `${seater}-Seater Tempo Traveller on Rent in Agra` : "Tempo Traveller on Rent in Agra";
    const opening = seater
      ? `A ${seater}-seater tempo traveller in Agra costs ₹${prices.fleet_per_km.tempo_traveller} per km with Agra SK Baghel Tour and Travels. It is suited to ${seaterBestFor[seater].toLowerCase()}, with pushback seating and luggage space. Driver allowance, minimum km/day and night halt charges are confirmed before booking. Call or WhatsApp ${contact.phoneDisplay} to book.`
      : `Hiring a tempo traveller in Agra costs ₹${prices.fleet_per_km.tempo_traveller} per km with Agra SK Baghel Tour and Travels. Choose from 12, 16, 18, 20 and 24-seater options for weddings, corporate trips and group sightseeing, with verified drivers and pushback seats. Driver allowance, minimum km/day and night halt charges are confirmed before booking. Call or WhatsApp ${contact.phoneDisplay} to book.`;
    return { title: label, meta: `${label} from ₹${prices.fleet_per_km.tempo_traveller}/km. Pushback seats, verified drivers and group travel options. Call or WhatsApp to book.`, opening, table: seater ? <table><caption>{label} details</caption><thead><tr><th>Seating</th><th>Price per km</th><th>Best for</th></tr></thead><tbody><tr><td>{seater}-seater</td><td>{money(prices.fleet_per_km.tempo_traveller)}/km</td><td>{seaterBestFor[seater]}</td></tr></tbody></table> : <table><caption>Tempo traveller rates in Agra</caption><thead><tr><th>Seater</th><th>Price per km</th><th>Best for</th></tr></thead><tbody>{Object.entries(seaterBestFor).map(([size, best]) => <tr key={size}><td>{size}-seater</td><td>{money(prices.fleet_per_km.tempo_traveller)}/km</td><td>{best}</td></tr>)}</tbody></table>, questions: seater ? [`What is the per km rate for a ${seater}-seater tempo traveller in Agra?`, "Are there any additional charges beyond the per km rate?", "Is a minimum distance required for booking?", "Is this tempo traveller suitable for outstation trips from Agra?"] : ["What is the per km rate for a tempo traveller in Agra?", "Which tempo traveller size should I choose?", "Is there a minimum distance or duration required?", "Can I take the tempo traveller out of Agra?"] };
  }
  const routeMap: Record<string, { from: string; to: string; fare: number }> = {
    "delhi-to-agra-taxi": { from: "Delhi", to: "Agra", fare: prices.routes_oneway.delhi_igi },
    "agra-to-delhi-taxi": { from: "Agra", to: "Delhi", fare: prices.routes_oneway.delhi_igi },
    "agra-to-jaipur-taxi": { from: "Agra", to: "Jaipur", fare: prices.routes_oneway.jaipur },
    "agra-to-mathura-taxi": { from: "Agra", to: "Mathura", fare: prices.routes_oneway.mathura },
    "agra-to-gwalior-taxi": { from: "Agra", to: "Gwalior", fare: prices.routes_oneway.gwalior },
  };
  if (routeMap[slug]) { const r = routeMap[slug]; return { title: `${r.from} to ${r.to} Taxi | One-Way ${money(r.fare)} | Agra SK Baghel Tour and Travels`, meta: `${r.from} to ${r.to} one-way taxi ${money(r.fare)}. Sedan, Ertiga and Innova Crysta available with verified drivers. Book on WhatsApp.`, opening: `A one-way taxi from ${r.from} to ${r.to} costs ${money(r.fare)} with Agra SK Baghel Tour and Travels. Choose a Sedan (${money(prices.fleet_per_km.sedan)}/km), Ertiga (${money(prices.fleet_per_km.ertiga)}/km) or Innova Crysta (${money(prices.fleet_per_km.innova_crysta)}/km), subject to route confirmation. Call or WhatsApp ${contact.phoneDisplay} to book.`, table: <table><caption>{r.from} to {r.to} one-way fares</caption><thead><tr><th>Vehicle</th><th>Seats</th><th>Per-km rate</th><th>One-way fare</th></tr></thead><tbody><tr><td>Sedan</td><td>4+1</td><td>{money(prices.fleet_per_km.sedan)}/km</td><td>{money(r.fare)}</td></tr><tr><td>Ertiga</td><td>6+1</td><td>{money(prices.fleet_per_km.ertiga)}/km</td><td>Confirm at booking</td></tr><tr><td>Innova Crysta</td><td>6+1</td><td>{money(prices.fleet_per_km.innova_crysta)}/km</td><td>Confirm at booking</td></tr></tbody></table>, questions: [`Is toll included in the ${r.from} to ${r.to} fare?`, `Which vehicles are available from ${r.from}?`, `Do you pick up from ${r.from} airport or railway station?`] }; }
  if (slug === "same-day-agra-tour-from-delhi") return { title: "Same Day Agra Tour from Delhi | Private Car", meta: `Same day Agra tour by car with pickup from Delhi, Noida or Gurgaon. Taj Mahal and Agra Fort with a verified driver. From ${money(prices.tours.same_day_agra)}. Book on WhatsApp.`, opening: `Visit the Taj Mahal and Agra Fort in a single day with pickup from Delhi, Noida, Gurgaon or Ghaziabad. A private car with a verified driver starts from ${money(prices.tours.same_day_agra)}; Delhi-pickup pricing is confirmed before booking. Call or WhatsApp ${contact.phoneDisplay} to book.`, table: <table><caption>Sample same-day Agra itinerary</caption><thead><tr><th>Time</th><th>Stop</th></tr></thead><tbody>{[["06:00", "Pickup from Delhi/NCR"], ["09:30", "Taj Mahal"], ["13:00", "Lunch at own expense"], ["14:30", "Agra Fort"], ["18:00", "Drive back via Yamuna Expressway"], ["21:30", "Drop at Delhi"]].map(([time, stop]) => <tr key={time}><td>{time}</td><td>{stop}</td></tr>)}</tbody></table>, questions: ["Can you visit the Taj Mahal and Agra Fort in one day?", "What time should you leave Delhi?", "Private car or train: which is better for Delhi–Agra?", "What is included and excluded in the same-day tour?"] };
  if (slug === "taj-mahal-taxi-service" || slug === "agra-fatehpur-sikri-one-day-tour") return { title: "Taj Mahal Taxi Service Agra | One-Day & Full-Day Cabs", meta: `Book a Taj Mahal taxi in Agra. 8h/80km ${money(prices.local_packages["8h_80km"])}, 12h/120km ${money(prices.local_packages["12h_120km"])}. Near Taj East Gate. Call or WhatsApp.`, opening: `Our Taj Mahal taxi service covers the Taj Mahal, Agra Fort and Mehtab Bagh, with 8-hour/80-km packages at ${money(prices.local_packages["8h_80km"])} and 12-hour/120-km packages at ${money(prices.local_packages["12h_120km"])}. We are based near Taj East Gate. Call or WhatsApp ${contact.phoneDisplay} to book.`, table: <table><caption>Taj Mahal taxi packages in Agra</caption><thead><tr><th>Package</th><th>Hours / km</th><th>Price</th></tr></thead><tbody><tr><td>Taj Mahal Day Trip</td><td>8 hrs / 80 km</td><td>{money(prices.local_packages["8h_80km"])}</td></tr><tr><td>Taj Mahal Full Day</td><td>12 hrs / 120 km</td><td>{money(prices.local_packages["12h_120km"])}</td></tr></tbody></table>, questions: ["What does the one-day Taj Mahal taxi package include?", "Do you provide railway station and airport pickup?", "Can I add Fatehpur Sikri to the day trip?"] };
  return { title: `${cityTitle(slug)} | Agra SK Baghel Tour and Travels`, meta: "Private Agra taxi booking with verified drivers. Call or WhatsApp to confirm availability.", opening: `Private taxi bookings from Agra are available for ${cityTitle(slug)} with verified drivers and clear fare confirmation. Call or WhatsApp ${contact.phoneDisplay} with your date, route and group size.`, table: <table><caption>Booking information</caption><thead><tr><th>Service</th><th>Details</th></tr></thead><tbody><tr><td>Vehicle</td><td>Private chauffeur-driven taxi</td></tr><tr><td>Fare</td><td>Confirmed before booking</td></tr></tbody></table>, questions: ["Which vehicle is right for this journey?", "What is included in the fare?", "How do I book this taxi?"] };
}

export function SeoLandingPage({ slug }: { slug: SeoLandingSlug }) {
  const model = pageModel(slug);
  const canonical = `/en/${slug}/`;
  const related = slug.includes("tempo") ? "/en/fleet/" : slug.includes("taxi") ? "/en/routes/" : "/en/packages/";
  const schema = buildGraphSchema(buildLocalBusinessSchema({ includeAggregateRating: false }), buildBreadcrumbSchema([{ name: "Home", url: "/" }, { name: model.title, url: canonical }]));
  return <main id="main-content" className="marketing-page seo-landing-page"><JsonLd schema={schema} /><section className="marketing-hero"><p className="eyebrow">Agra SK Baghel Tour and Travels · Taj Ganj, Agra</p><h1>{model.title.split(" | ")[0]}</h1><p className="hero-copy">{model.opening}</p><div className="hero-actions"><a className="button button-primary" href={`tel:${contact.phone}`}>Call {contact.phoneDisplay}</a><a className="button button-whatsapp" href={`https://wa.me/${contact.whatsapp}?text=Hi%20SK%20Baghel%20Travels%2C%20I%20want%20to%20book`} target="_blank" rel="noreferrer">WhatsApp to book</a></div></section><section className="detail-content"><div className="fare-table-wrap">{model.table}</div><p className="muted-note">Toll, parking, interstate tax, driver allowance and night halt charges are confirmed for the route before booking.</p><h2>What should I know before booking?</h2><p>Call or WhatsApp with your travel date, pickup point, destination and group size. We confirm vehicle availability and the complete fare before the booking is finalized.</p>{model.questions.map((question) => <section key={question}><h2>{question}</h2><p>We provide a direct answer during fare confirmation based on your vehicle, route and travel date. The desk will explain inclusions, timing, pickup options and any applicable extras before you pay.</p></section>)}<h2>How do I book this service?</h2><ol><li>Call or WhatsApp {contact.phoneDisplay} with your date, route and group size.</li><li>We confirm the vehicle, timing and total fare.</li><li>Follow the booking instructions shared by the travel desk.</li></ol><p><a className="text-link" href={related}>Explore related {related.includes("fleet") ? "fleet options" : related.includes("routes") ? "Agra taxi routes" : "Agra tour packages"}</a> · <a className="text-link" href="/en/contact/">Contact the Agra travel desk</a></p></section></main>;
}
