/* GENERATED by scripts/render_pages.py from scripts/catalog.py — do not hand-edit. */
window.SKB = window.SKB || {};
SKB.contact = {
  "phone": "+919876543210",
  "phoneDisplay": "+91 98765 43210",
  "whatsapp": "919876543210",
  "email": "bookings@skbagheltravels.in",
  "address": "Near Taj East Gate Road, Taj Ganj, Agra, Uttar Pradesh 282001",
  "hours": "Bookings open 24×7",
  "mapsUrl": "https://maps.google.com/?q=Taj+Ganj+Agra",
  "gst": "09ABCDE1234F1Z5"
};
